### ISSUE TITLE
Cannot load './LLaVA-Lightening-7B-v1-1'

### ISSUE THREAD

**Issue by msra-jqxu** [mbzuai-oryx/Video-ChatGPT#22]
Hi, I followed the instruction in offline_demo.md and saved the Video-ChatGPT weights and the LLaVA-Lightening-7B-v1-1 weights in the current directory. Then I used this command for Offline Demo: python video_chatgpt/demo/video_demo.py --model-name ./LLaVA-Lightening-7B-v1-1 --projection_path ./video_chatgpt-7B.bin
but got an error: huggingface_hub.utils._validators.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: './LLaVA-Lightening-7B-v1-1'.
Is it the way I fill in --model_name wrong?

Thanks!

![image](https://github.com/mbzuai-oryx/Video-ChatGPT/assets/53702716/681398f5-32a8-40cf-b1fe-7806cba6f183)

**Comment by mmaaz60** [comment]
Hi @msra-jqxu,

Thank You for your interest in our work. I tried reproducing the issue you are facing but everything is working fine for me. Could you try hard-coding the arguments directly to the `video_chatgpt/demo/video_demo.py` file instead of passing as command line arguments?

Further, please have a look at the https://github.com/huggingface/diffusers/issues/736 and it may help in resolving the issue.

Please let me know if it works or you have any further questions. Thank You.
