### ISSUE TITLE
Question about running video-chatgpt demo offline

### ISSUE THREAD

**Issue by jhj7905** [mbzuai-oryx/Video-ChatGPT#23]
@mmaaz60 
In Advance, Thank you for providing great work.
I have question about running video-chatgpt demo offline.
when i uploaded the video with 'Upload Video' button, it did not work after 10 minutes.....
Can you confirm it ? and tell me how to use it correctly?

**Comment by mmaaz60** [comment]
Hi @jhj7905,

Thank You for your interest in our work. Please note that you have drop/drag the video to the place holder first before pressing the upload video button. I hope it will help, otherwise please share the exact steps you are following and I may be able to identify the issue. Thank You.

**Comment by ceyxasm** [comment]
Same issue. 
Let be explain clearly @mmaaz60 
The demo is working fine as in the GUI.
However when we upload the video, it takes forever to process
![image](https://github.com/mbzuai-oryx/Video-ChatGPT/assets/73417805/623eedd2-716b-4fba-af0d-db2d95e8fad5)

I have seen this waiting time for for 20 minutes plus.

**Comment by hanoonaR** [comment]
Hi @ceyxasm,

Thank you for bringing this to our attention and our apologies for the inconvenience you're experiencing. Currently, the demo is hosted locally, and the delay you're facing with the video processing time is due to ongoing maintenance work, which has unfortunately resulted in bandwidth issues. This is causing some unexpected latency, especially for tasks like video upload and processing. We anticipate that the issue will be solved in a few days. We appreciate your understanding and patience during this time.

In the meantime, we recommend using the offline version of the demo if possible. The instructions for the offline demo can be found [here](https://github.com/mbzuai-oryx/Video-ChatGPT/blob/main/docs/offline_demo.md). This should provide a more immediate solution. If you have any questions or need assistance with the offline demo, feel free to ask. We are here to help!

**Comment by ceyxasm** [comment]
Hey @hanoonaR 
The latency that I am facing is in the offline demo only. I have done the local setup just as it demanded. However, even when running locally; processing time is 10 minutes and more. In fact, the OC is also facing the same issue

**Comment by mmaaz60** [comment]
Hi @ceyxasm,

Thank You for the clarification. I tried reproducing the issue following the instructions at [Video-ChatGPT offline demo](https://github.com/mbzuai-oryx/Video-ChatGPT/blob/main/docs/offline_demo.md) but couldn't reproduce it. For me the processing of a 1.5 minutes long video took a few seconds only. I am running it on NVIDIA A100-40GB GPU.

To further analyze the issue you are facing I request the following information,
1. What hardware (GPU) you are running the demo on? Is something else is also running on the GPU?
2. Have you followed the instructions at [Installation](https://github.com/mbzuai-oryx/Video-ChatGPT/tree/main#installation-wrench) to create the environment? Please share the versions of PyTorch, Transformers and Gradio in your environment.
3. Please share the screenshot of the whole browser screen to better understand the problem. If you can share a small screen recording, that would be great.

Also from the screenshot you shared, it looks like the system has not yet started processing the video (its displaying queue). So, it could either be because it still uploading the video (in offline demo it just equivalent to copy it to a temp location) or the GPU does not have enough resources to process the video or may be the program is stuck. Providing the above requested information would definitely help in understanding the problem better.

Thank You and looking forward to your response.

**Comment by Adeelyousaf** [comment]
Hi,  can we generate multiple captions per video using the demo?

**Comment by mmaaz60** [comment]
> Hi, can we generate multiple captions per video for one question using the offline demo?

Hi @Adeelyousaf,

Yes it is possible. We used Vicuna which is a generative language model and produce different responses in distinct iterations, each being contextually relevant to the asked question.

**Comment by yuu2704** [comment]
@mmaaz60
Thank you for your excellent work.
I have some problems running the offline demo of Video ChatGPT. 
It is a similar symptom to the first problem in this thread, but in my environment, the following error has been identified when uploading the video.

Traceback (most recent call last):
  File "/home/yanai-lab/nakamizo-y/.conda/envs/video_chatgpt2/lib/python3.10/site-packages/gradio/queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "/home/yanai-lab/nakamizo-y/.conda/envs/video_chatgpt2/lib/python3.10/site-packages/gradio/queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "/home/yanai-lab/nakamizo-y/.conda/envs/video_chatgpt2/lib/python3.10/site-packages/gradio/queueing.py", line 456, in get_message
    return PredictBody(**data), True
  File "/home/yanai-lab/nakamizo-y/.conda/envs/video_chatgpt2/lib/python3.10/site-packages/pydantic/main.py", line 150, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'fn_index': 12, 'data': ...on_hash': '7xau06wrutn'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.0.3/v/missing

**Comment by mmaaz60** [comment]
Hi @yuu2704,

Thank you for your interest in our work. To better assist you, may I know the `gradio version` you are using? Thanks

**Comment by yuu2704** [comment]
> Hi @yuu2704,
> 
> Thank you for your interest in our work. To better assist you, may I know the `gradio version` you are using? Thanks

Thank you for your prompt reply.

I am using gradio version 3.23.0. I am also complying with the requirements.txt file for other libraries.

**Comment by ktr-hubrt** [comment]
> > Hi @yuu2704,
> > Thank you for your interest in our work. To better assist you, may I know the `gradio version` you are using? Thanks
> 
> Thank you for your prompt reply.
> 
> I am using gradio version 3.23.0. I am also complying with the requirements.txt file for other libraries.

Hi, i met the same problem when i run the offline demo on various machines. Have you solved it?

**Comment by mmaaz60** [comment]
Hi @yuu2704 @ktr-hubrt,

Please try installing the below version of `pydantic` and let me know if it solves the issue. Thanks.

```
pip install pydantic==1.10.7
```

**Comment by ktr-hubrt** [comment]
> Hi @yuu2704 @ktr-hubrt,
> 
> Please try installing the below version of `pydantic` and let me know if it solves the issue. Thanks.
> 
> ```
> pip install pydantic==1.10.7
> ```

Thanks, it works.
