### ISSUE TITLE
Website not working properly

### ISSUE THREAD

**Issue by Muhammad-Soomro** [mbzuai-oryx/Video-ChatGPT#39]
Hey, I hope you guys are doing well i want to use the vdeio-ChatGPT for a POC but the chatting feature is not working can you please look into this ASAP. Thank you

**Comment by mmaaz60** [comment]
Hi @Muhammad-Soomro,

Thank you for creating the issue and apologies for the inconvenience caused. The demo is restored, however this frequent disruption is happening due to the some network related issues on our end. We are trying to find an alternative way of hosting the demo.

Meanwhile, if you want to have a smoother version of demo, I would highly recommend you to host it offline. The instructions are available at [Running Video-ChatGPT demo offline](https://github.com/mbzuai-oryx/Video-ChatGPT/blob/main/docs/offline_demo.md).

**Comment by Muhammad-Soomro** [comment]
Hey can you please guide me what can i run the inference on the aws sagemaker ( from the hugging face )?

**Comment by hanoonaR** [comment]
Hi @Muhammad-Soomro,

Please refer to issue #41 

Thank you.
