### ISSUE TITLE
[benchmark] Some questions about the details to generate files in step 1 during `Video-based Generative Performance Benchmarking`.

### ISSUE THREAD

**Issue by aopolin-lv** [mbzuai-oryx/Video-ChatGPT#47]
Hello, follow the instructions of step 1 in [quantitative_evaluation](https://github.com/mbzuai-oryx/Video-ChatGPT/tree/main/quantitative_evaluation), I obtain three files:
1. one file generated with `generic_qa.json` and [run_inference_benchmark_general.py](https://github.com/mbzuai-oryx/Video-ChatGPT/blob/main/video_chatgpt/eval/run_inference_benchmark_general.py)
2. one file generated with `consistency_qa.json` and [run_inference_benchmark_consistency.py](https://github.com/mbzuai-oryx/Video-ChatGPT/blob/main/video_chatgpt/eval/run_inference_benchmark_consistency.py)
3. one file generated with `temporal_qa.json` and [run_inference_benchmark_general.py](https://github.com/mbzuai-oryx/Video-ChatGPT/blob/main/video_chatgpt/eval/run_inference_benchmark_general.py)

Then, do I need to generate any other file? And how does them function in step 2? More specifically, if I want to evaluate correctness and detailed, which file generated in step1 should I input to the `pred_path` in step 2 command?

**Comment by hanoonaR** [comment]
Hi @Aopolin-Lv,

Apologies for the late reply.
Note that the question-answer pairs (gt_file) are the same for correctness, detailed orientation and Contextual understanding.

So, In your case, you want to evaluate the correctness and detailed orientation criteria:
If you run the first step using the below command: the predictions are stored in `--output_dir <output-dir-path>`.

``python video_chatgpt/eval/run_inference_benchmark_general.py \
    --video_dir <path-to-directory-containing-videos> \
    --gt_file <ground-truth-file-containing-question-answer-pairs> \
    --output_dir <output-dir-path> \
    --output_name <output-file-name> \
    --model-name <path-to-LLaVA-Lightening-7B-v1-1> \
    --projection_path <path-to-Video-ChatGPT-weights>``

In order to evaluate the criteria, you will need to pass the same '--output_dir <output-dir-path>' as the pred_path [here](https://github.com/mbzuai-oryx/Video-ChatGPT/blob/915c18a2d4023fc2274484ebacd639b331a1efd8/quantitative_evaluation/evaluate_benchmark_1_correctness.py#L11).

Hope its clear now.
