### ISSUE TITLE
Can I deal with Chinese video? 

### ISSUE THREAD

**Issue by zhangyuereal** [mbzuai-oryx/Video-ChatGPT#81]
Can I deal with Chinese video? 
Like，ask questions and get answer in Chinese?

Need I retrain any model?

**Comment by mmaaz60** [comment]
Hi @zhangyuereal,

Our base LLM model is Vicuna which is reasonably good in Chinese. Although Video-ChatGPT is trained using English video conversations, you can ask questions and get response back in Chinese. However, in order to get optimal performance, it is recommended to translate VideoInstruct data to Chinese and retrain the model.

I hope it will be helpful. Thank You.
